name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Just runs the buf linter
    - name: make lint
      run: make lint
    # Attempts to build using `protoc`
    - name: make protoc
      run: make protoc
    # Create an actual build, then diff it to make sure build is up to date
    - name: check build
      run: |
        make build
        # --exit-code causes it to fail if there are differences
        git diff --name-only --diff-filter=AM --exit-code
