name: CI

env:
  go-version: "1.19"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: lint and check build
        run: |
          # Runs the buf linter and checks for breaking changes
          make https

          # Attempts to build using `protoc`. Probably redundant given the next step.
          make protoc

          # Create an actual build, then diff it to make sure build is up to date
          make check
